version: "3.9"

services:
  spawnpoint:
    build: .
    container_name: spawnpoint
    restart: unless-stopped
    ports:
      - "40400:40400"
    environment:
      - STEAM_HOST=192.168.1.160
    volumes:
      - steam_cache:/home/steam/Steam
      - games_data:/home/steam/games

volumes:
  steam_cache:
    driver: local
  games_data:
    driver: local